stages:
  - build
  - test
  - cypress

build:
  stage: build
  script:
    - cd ./BackEnd
    - mvn $MAVEN_CLI_OPTS compile
test:
  stage: test
  dependencies:
    - build
  script:
    - cd ./Backend
    - mvn $MAVEN_CLI_OPTS test

cypress:
  stage: cypress
  script:
   - cd ./Frontend
   - npx cypress run
after_script:
    - echo "End CI"
